### ISSUE TITLE
Re-Installation fails

### ISSUE THREAD

**Issue by Flowr-es** [matrix-io/matrix-creator-init#51]
I upgraded from jessie to stretch... now I'm fighting again with your software setup for the matrix creator :-(

I removed all matrix packages and tried to reinstall...

This is what happend:

Created symlink from /etc/systemd/system/multi-user.target.wants/matrixio-devices-firmware.service to /lib/systemd/system/matrixio-devices-firmware.service.
Enabling SPI
Disable UART console
Installing esptool
Requirement already satisfied (use --upgrade to upgrade): esptool in /usr/local/lib/python2.7/dist-packages
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1293, in prepare_files
    subreq = InstallRequirement(req, req_to_install)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 109, in __init__
    self.prereleases = any([is_prerelease(x[1]) and x[0] != "!=" for x in self.req.specs])
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 739, in is_prerelease
    return any([any([y in set(["a", "b", "c", "rc", "dev"]) for y in x]) for x in parsed])
TypeError: 'int' object is not iterable

Storing debug log for failure in /root/.pip/pip.log

Any suggestions?

**Comment by Flowr-es** [comment]
This fixes my bug:

sudo apt-get install python-pip
